"""Appendix table of every frozen-set arm, generated from analysis-output/e1/e1_scores.json.

Writes paper_arr2026/sections/A_e1_arms.tex. Numbers are never typed by hand.

    python e1_tables.py
"""
from __future__ import annotations

import json
from pathlib import Path

SCORES = Path("analysis-output/e1/e1_scores.json")
OUT = Path("paper_arr2026/sections/A_e1_arms.tex")

GROUPS = [
    ("Unsteered", [("unsteered_s42", "seed 42 (reference)"), ("unsteered_s43", "seed 43"),
                   ("unsteered_s44", "seed 44"), ("unsteered_leace_runner", "seed 42, LEACE runner")]),
    ("Prompting", [("prompt_min", "minimal prompt"), ("prompt_explicit", "explicit prompt"),
                   ("prompt_explicit_cad_k40", "explicit + projection $k{=}40$")]),
    ("CAD projection, $\\alpha{=}1$", [(f"cad_proj_k{k}", f"$k{{=}}{k}$") for k in (1, 5, 10, 20, 40, 80)]
     + [("cad_proj_kauto", "$k$ at 80\\% variance (33/36)"),
        ("cad_proj_kauto_FULLPOOL", "same, full-pool fit (leak ctrl.)"),
        ("cad_proj_probe", "rank 1, supervised probe direction"),
        ("cad_proj_meandiff", "rank 1, mean-difference direction")]),
    ("CAD additive", [(f"add_probe_a{a}", f"probe $\\alpha{{=}}{a}$") for a in (3, 5, 7, 9)]
     + [(f"add_meandiff_a{a}", f"mean-diff.\\ $\\alpha{{=}}{a}$") for a in (3, 5, 7, 8)]),
    ("LEACE, rank $k$", [(f"leace_k{k}", f"$k{{=}}{k}$") for k in (1, 5, 10, 20, 40, 80)]),
    ("Published baselines", [("caa", "CAA L14 $\\alpha{=}1$"),
                             ("caa_FULLPOOL", "CAA, full-pool fit (leak ctrl.)"),
                             ("fairsteer", "FairSteer L29 $\\alpha{=}2$"), ("sadi", "SADI $s{=}10$"),
                             ("angular", "Angular max-sim L23 $150^\\circ$")]),
]


def f(x: float, nd: int = 2, sign: bool = False) -> str:
    s = f"{x:+.{nd}f}" if sign else f"{x:.{nd}f}"
    return s.replace("-", "$-$")


def ci(c: list[float], nd: int = 2) -> str:
    return f"[{f(c[0], nd)}, {f(c[1], nd)}]"


def main() -> int:
    S = json.loads(SCORES.read_text())["summary"]
    rows = []
    for title, arms in GROUPS:
        rows.append(f"\\multicolumn{{7}}{{@{{}}l}}{{\\textit{{{title}}}}} \\\\")
        for arm, label in arms:
            s = S[arm]
            flag = ", ".join(s["degenerate"]) or ""
            rows.append(" & ".join([
                label,
                f"{f(s['d'])} {ci(s['d_ci'])}",
                f"{s['dmed_pct']:.0f}".replace("-", "$-$"),
                f"{f(s['dq_llama'], sign=True)} {ci(s['dq_llama_ci'])}",
                f"{f(s['dq_qwen'], sign=True)} {ci(s['dq_qwen_ci'])}",
                f"{s['unique']:.2f} / {s['parse_fail']:.2f}",
                flag]) + " \\\\")
        rows.append("\\midrule")
    rows[-1] = "\\bottomrule"
    OUT.write_text("% GENERATED by e1_tables.py from analysis-output/e1/e1_scores.json. Do not edit.\n"
                   "\\begin{table*}[t]\n\\centering\\scriptsize\n\\setlength{\\tabcolsep}{3pt}\n"
                   "\\begin{tabular}{@{}lllllll@{}}\n\\toprule\n"
                   "Arm & $d$ [95\\% CI] & $\\Delta$Med\\% & $\\Delta$Q Llama [CI] & $\\Delta$Q Qwen [CI] "
                   "& Uniq / Fail & Flag \\\\\n\\midrule\n"
                   + "\n".join(rows) + "\n\\end{tabular}\n"
                   "\\caption{Every arm of the frozen-set test, 250 items each. Reference: unsteered seed 42. "
                   "Intervals are $95\\%$ bootstrap intervals over the 50 questions (2{,}000 resamples). "
                   "Uniq is the fraction of distinct responses and Fail the fraction the Llama judge "
                   "could not parse. Flags use the thresholds of Section~\\ref{sec:frontier}.}\n"
                   "\\label{tab:e1all}\n\\end{table*}\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
